---
- import_playbook: prerequisites.yaml
- import_playbook: plex.yaml
- import_playbook: transmission.yaml
- import_playbook: monitoring.yaml
- import_playbook: mastodon.yaml
- import_playbook: garunner.yaml
- import_playbook: ha.yaml
- import_playbook: pihole.yaml
- import_playbook: z2m.yaml
- import_playbook: motion.yaml
- import_playbook: mjpeg.yaml